name: menstrudel
description: "Your private, offline, menstrual cycle tracker."
publish_to: 'none'

version: 3.2.0+20

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  collection: ^1.19.1
  shared_preferences: ^2.5.3
  dynamic_color: ^1.8.1
  flutter_timezone: ^5.0.0
  fl_chart: ^1.0.0
  table_calendar: ^3.2.0
  path: ^1.9.1
  flutter_colorpicker: ^1.1.0
  provider: ^6.1.5+1
  watch_connectivity: ^0.2.3
  local_auth: ^3.0.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.0
  file_picker: ^10.3.3
  home_widget: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
