name: SonarCloud Scan

on:
  workflow_run:
    workflows: ["SonarQube Build and Test"] 
    types:
      - completed

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download and set up SonarScanner
        env:
          SONAR_SCANNER_VERSION: 5.0.1.3006 
        run: |
          sudo apt-get install -y unzip
          curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux.zip
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          rm $HOME/.sonar/sonar-scanner.zip
          echo "$HOME/.sonar/sonar-scanner-${SONAR_SCANNER_VERSION}-linux/bin" >> $GITHUB_PATH

      - name: Run SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.organization=j-shw \
            -Dsonar.projectKey=J-shw_Menstrudel \
            -Dsonar.flutter.coverage.lcovReportPath=lcov.info \
            ${{ github.event.workflow_run.event == 'pull_request' && format('
              -Dsonar.pullrequest.key={0}
              -Dsonar.pullrequest.branch={1}
              -Dsonar.pullrequest.base={2}
              -Dsonar.pullrequest.headsha={3}
              ', 
              github.event.workflow_run.pull_requests[0].number, 
              github.event.workflow_run.pull_requests[0].head.ref, 
              github.event.workflow_run.pull_requests[0].base.ref,
              github.event.workflow_run.head_sha) 
            }}
            ${{ github.event.workflow_run.event == 'push' && format('
              -Dsonar.branch.name={0}
              ', 
              github.event.workflow_run.head_branch) 
            }}