name: SonarQube Scan

on:
  workflow_run:
    workflows: ["SonarQube Build and Test"] 
    types:
      - completed

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.flutter.coverage.lcovReportPath=lcov.info

            ${{ github.event.workflow_run.event == 'pull_request' && format('
              -Dsonar.pullrequest.key={0}
              -Dsonar.pullrequest.branch={1}
              -Dsonar.pullrequest.base={2}
              -Dsonar.pullrequest.headsha={3}
              ', 
              github.event.workflow_run.pull_requests[0].number, 
              github.event.workflow_run.pull_requests[0].head.ref, 
              github.event.workflow_run.pull_requests[0].base.ref,
              github.event.workflow_run.head_sha) 
            }}

            ${{ github.event.workflow_run.event == 'push' && format('
            -Dsonar.branch.name={0}
            ', 
            github.event.workflow_run.head_branch) }}